name: Terraform Init & Plan

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      CONFIG_DIR:
        required: true
        default: './infrastructure'
        description: Directory containing Terraform configuration files.
        type: string

jobs:
  terraform:
    name: Terraform Init & Plan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6  # or your preferred version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false
    
    